import Footer from "@/components/Layout/Footer";
import "./globals.css";
export const metadata = {
  title: "Genrobotics",
  description: "Generated by Next JS",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
