import Footer from "@/components/Layout/Footer";
import "./globals.css";
import { roboto, anton, bayon } from './fonts';

export const metadata = {
  title: "Genrobotics",
  description: "Generated by Next JS",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${roboto.variable} ${anton.variable} ${bayon.variable}`}>
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
